FROM python:3.9-slim

WORKDIR /app

COPY ./requirements.txt .
COPY ./src/main.py .
COPY ./src/notebooks/ ./notebooks/
COPY ./gcp.secrets.json .

ENV GOOGLE_APPLICATION_CREDENTIALS="/app/gcp.secrets.json"

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    mkdir /app/notebooks/output

CMD ["python3", "main.py"]